spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    gcp:
      storage:
        credentials:
          location: ${LOCATION}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql : trace

springDoc:
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
